package com.github.plippe.news.scrapy.parsers

import cats.implicits._
import org.http4s.Uri
import org.scalatest._

class IndependentIeArticleListParserSpec
    extends FunSuite
    with ParserSpecHelper {

  test("IndependentIeArticleListParser should return all uris in html file") {
    val expected = Seq(
      "https://www.independent.ie/irish-news/agricultural-contractor-killed-following-a-shooting-overnight-at-a-farmhouse-is-named-locally-37454064.html",
      "https://www.independent.ie/irish-news/courts/man-who-stabbed-burned-and-beat-partner-in-vicious-unprovoked-attack-jailed-for-nine-and-a-half-years-37453666.html",
      "https://www.independent.ie/sport/rugby/international-rugby/raidhr-oconnor-schmidts-selection-will-be-telling-as-november-calls-have-real-world-cup-ramifications-37452235.html",
      "https://www.independent.ie/business/jobs/employment-blow-for-midlands-as-bord-na-mna-announces-430-job-losses-37453627.html",
      "https://www.independent.ie/irish-news/courts/dublin-couple-fail-in-legal-claim-as-they-deny-house-apartment-and-cash-are-proceeds-of-crime-37453909.html",
      "https://www.independent.ie/irish-news/education/its-going-to-be-difficult-plan-to-provide-alternative-accommodation-for-closed-schools-by-end-of-midterm-break-37453735.html",
      "https://www.independent.ie/irish-news/courts/cage-fighter-drops-car-crash-injury-claim-after-insurer-produces-video-37452587.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/the-final-debate-how-all-six-presidential-candidates-fared-37452576.html",
      "https://www.independent.ie/life/family/what-it-feels-like-to-end-up-losing-your-home-37447512.html",
      "https://www.independent.ie/irish-news/courts/irish-woman-traumatised-by-violent-fianc-when-she-killed-him-claim-37452523.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/watch-im-not-voting-for-donald-trump-kids-discuss-the-irish-presidential-election-37450020.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/presidential-debate-how-do-the-candidates-think-they-fared-37453245.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/sinn-fein-presidential-candidate-liadh-ni-riada-dismisses-salary-controversy-as-no-big-deal-37453611.html",
      "https://www.independent.ie/opinion/comment/storm-before-the-calm-rivals-try-to-take-down-michael-d-over-flight-37452535.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/n-riada-defends-opposition-to-migrant-rescue-mission-in-mediterranean-37452534.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/dr-theresa-reidy-explains-the-role-of-irish-president-pretty-powerless-but-six-important-rules-and-responsibilities-37448338.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/deportation-laws-should-be-upheld-casey-37452521.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/watch-i-think-hes-out-of-the-lions-den-is-he-can-you-name-all-of-the-presidential-candidates-37439856.html",
      "https://www.independent.ie/irish-news/politics/the-floating-voter-dragons-doing-each-other-no-favours-in-presidential-race-says-gavin-duffy-37448895.html",
      "https://www.independent.ie/style/fashion/fashion-news/dutch-queen-mxima-chooses-an-irish-designer-for-her-muchhyped-state-visit-to-the-uk-37453878.html",
      "https://www.independent.ie/life/family/parenting/pinterest-parenting-how-millennials-are-upping-the-ante-37447515.html",
      "https://www.independent.ie/life/travel/ireland/irelands-30-best-autumn-walks-with-a-cosy-meal-or-pint-at-the-finish-37439356.html",
      "https://www.independent.ie/life/food-drink/recipes/im-looking-at-her-handwriting-remembering-her-and-those-simple-times-rtes-mary-kennedy-shares-her-mothers-recipes-37429832.html",
      "https://www.independent.ie/style/celebrity/celebrity-news/meghan-markle-rushed-out-of-fijian-market-after-just-seven-minutes-due-to-security-issue-37452848.html",
      "https://www.independent.ie/irish-news/courts/murdered-accused-asked-to-see-obriens-partner-to-tell-her-the-truth-court-hears-37453974.html",
      "https://www.independent.ie/irish-news/courts/dublin-bus-driver-denies-careless-driving-causing-death-of-a-cyclist-37452813.html",
      "https://www.independent.ie/opinion/columnists/colette-browne/colette-browne-after-such-a-vapid-campaign-can-anyone-honestly-believe-one-of-the-challengers-will-do-a-better-job-than-michael-d-has-37452376.html",
      "https://www.independent.ie/irish-news/wrap-up-warm-arctic-blast-heading-our-way-for-the-bank-holiday-37452421.html",
      "https://www.independent.ie/irish-news/courts/jury-unable-to-reach-verdict-in-trial-of-woman-accused-of-slicing-civil-servants-throat-on-street-37453678.html",
      "https://www.independent.ie/world-news/europe/watch-police-identify-man-in-ryanair-racist-rant-incident-37452546.html",
      "https://www.independent.ie/world-news/asia-pacific/flaunt-your-wealth-challenge-goes-viral-in-china-with-people-falling-out-of-cars-with-luxury-goods-37452849.html",
      "https://www.independent.ie/sport/rugby/the-left-wing/i-was-thinking-have-i-made-a-big-mistake-here-leinster-star-on-his-decision-to-change-positions-37453387.html",
      "https://www.independent.ie/irish-news/gardai-seeking-assistance-in-locating-missing-girl-17-37453431.html",
      "https://www.independent.ie/world-news/north-america/president-trump/donald-trump-says-someone-really-messed-up-in-coverup-of-khashoggi-death-as-sanctions-announced-37452770.html",
      "https://www.independent.ie/irish-news/harris-warns-terrorism-not-the-only-challenge-to-garda-from-brexit-37453217.html",
      "https://www.independent.ie/life/home-garden/homes/four-keenly-priced-homes-on-the-market-within-100km-of-the-m50-37435237.html",
      "https://www.independent.ie/irish-news/courts/man-22-tricked-teenage-boys-into-sharing-explicit-images-by-pretending-to-be-a-girl-37452386.html",
      "https://www.independent.ie/sport/soccer/other-soccer/i-shirt-the-sheriff-bohemians-new-strip-honours-reggae-hero-bob-marley-37452599.html",
      "https://www.independent.ie/irish-news/politics/sinn-fein-mep-accuses-colleagues-of-scaremongering-at-the-behest-of-lobbyists-in-balloon-row-37453260.html",
      "https://www.independent.ie/irish-news/courts/catherine-nevins-conviction-for-murdering-husband-does-not-prove-her-guilt-37452559.html",
      "https://www.independent.ie/sport/rugby/the-left-wing/the-left-wing-rory-oloughlin-and-james-tracy-on-toulouse-their-leinster-journey-and-working-with-joe-schmidt-37451896.html",
      "https://www.independent.ie/business/small-business/your-stories/i-wasnt-the-right-person-i-was-the-only-person-meadows-byrnes-helen-coughlans-rise-from-shop-floor-to-store-director-37412497.html",
      "https://www.independent.ie/life/home-garden/how-star-tv-architect-roisin-keeps-it-real-read-her-failsafe-design-tips-37441211.html",
      "https://www.independent.ie/life/family/mothers-babies/dear-meghan-markle-heres-my-advice-from-one-expectant-mum-to-another-37427760.html",
      "https://www.independent.ie/life/is-the-tradition-of-the-unannounced-house-visit-dying-in-ireland-37427251.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/nicola-anderson-peter-casey-left-quickly-after-getting-the-exposure-hed-come-for-37436253.html",
      "https://www.independent.ie/irish-news/blasphemy-referendum/andrea-martin-there-is-no-place-in-our-constitution-for-a-blasphemy-offence-for-which-no-one-will-be-convicted-its-a-sham-37426016.html",
      "https://www.independent.ie/irish-news/presidential-election-2018/listen-presidential-candidate-peter-casey-sparks-outrage-with-his-racist-remarks-on-travellers-37428508.html",
      "https://www.independent.ie/irish-news/education/up-to-40-schools-are-in-danger-of-closure-37452533.html",
      "https://www.independent.ie/irish-news/tuam-babies-papal-silence-as-nuns-2-5m-offer-for-exhumations-branded-too-low-37452555.html",
      "https://www.independent.ie/business/brexit/lack-of-decisionmaking-in-north-increases-the-threat-of-terrorism-37452529.html",
      "https://www.independent.ie/irish-news/courts/trial-set-for-boys-accused-of-ana-murder-37452550.html",
      "https://www.independent.ie/irish-news/politics/school-bus-firms-failing-to-carry-out-maintenance-37452531.html",
      "https://www.independent.ie/irish-news/courts/1m-lodged-in-court-as-emmas-children-wait-to-buy-a-new-family-home-37452585.html",
      "https://www.independent.ie/style/galleries/social-sightings-look-the-business-event-at-mansion-house-37454227.html",
      "https://www.independent.ie/style/galleries/social-sightings-irish-tatler-women-of-the-year-awards-at-the-clayton-hotel-37450439.html",
      "https://www.independent.ie/world-news/asia-pacific/in-pictures-china-opens-hong-kongmainland-55km-long-sea-bridge-37448764.html",
      "https://www.independent.ie/style/galleries/british-royal-tour-meghan-and-harry-in-australia-37424846.html",
      "https://www.independent.ie/style/galleries/guests-arrive-at-windsor-castle-for-princess-eugenies-wedding-37412126.html",
      "https://www.independent.ie/style/galleries/royal-wedding-princess-eugenies-big-day-in-pictures-37413456.html",
      "https://www.independent.ie/style/galleries/social-sightings-stellars-10th-birthday-party-at-krystle-37409757.html",
      "https://www.independent.ie/style/galleries/in-pictures-american-music-awards-2018-amas-red-carpet-37403593.html",
      "https://www.independent.ie/irish-news/galleries/in-pictures-budget-day-2019-37399277.html",
      "https://www.independent.ie/sport/rugby/international-rugby/this-thing-snowballed-big-time-conor-murray-explains-injury-silence-as-he-targets-latenovember-return-37454274.html",
      "https://www.independent.ie/sport/soccer/champions-league/how-can-you-reach-that-level-jose-mourinho-tells-man-united-board-to-sign-top-players-or-get-left-behind-37452168.html",
      "https://www.independent.ie/sport/rugby/munster-rugby/munster-dismiss-reports-linking-head-coach-van-graan-to-role-with-the-bulls-37452597.html",
      "https://www.independent.ie/sport/soccer/champions-league/im-surprised-they-keep-relatively-still-didi-hamann-baffled-by-reaction-of-man-united-fans-to-dross-37452889.html",
      "https://www.independent.ie/sport/rugby/international-rugby/dubliner-ian-mckinley-picked-on-the-italian-bench-for-clash-with-ireland-in-chicago-37454315.html",
      "https://www.independent.ie/sport/rugby/leinster-rugby/pure-ste-sean-obrien-gives-a-very-sean-obrien-response-to-leinsterall-blacks-comparisons-37452945.html",
      "https://www.independent.ie/business/personal-finance/property-mortgages/central-bank-proposals-would-allow-credit-unions-to-offer-home-loans-in-a-meaningful-way-37453485.html",
      "https://www.independent.ie/business/irish/profit-jumps-80pc-at-kerrybased-fintech-fexco-37453227.html",
      "https://www.independent.ie/business/commercial-property/buyer-sought-for-dublin-landings-apartments-37451374.html",
      "https://www.independent.ie/business/irish/aryzta-800m-cash-call-doomed-to-fail-claims-shareholder-37451363.html",
      "https://www.independent.ie/business/irish/france-claims-agreement-on-controversial-eu-digital-tax-is-close-37451377.html",
      "https://www.independent.ie/business/irish/behind-the-rosy-headlines-ireland-still-trails-behind-its-peers-in-the-eu-37451383.html",
      "https://www.independent.ie/business/brexit/donald-tusk-responds-to-nigel-farage-brexiteers-are-100pc-responsible-for-bringing-back-problem-of-irish-border-37452973.html",
      "https://www.independent.ie/style/celebrity/celebrity-news/kate-middleton-dazzles-in-princess-dianas-tiara-at-buckingham-palace-dinner-37451979.html",
      "https://www.independent.ie/style/celebrity/celebrity-news/part-of-me-feels-like-to-put-a-cork-in-it-after-this-but-i-feel-we-make-really-great-kids-jamie-dornan-37452986.html",
      "https://www.independent.ie/style/fashion/fashion-news/you-dont-admit-to-buying-dresses-rachel-bloom-didnt-know-she-was-supposed-to-keep-her-emmys-gown-a-secret-37452907.html",
      "https://www.independent.ie/style/celebrity/celebrity-news/i-didnt-think-i-was-good-looking-enough-for-tv-says-rising-rte-star-doireann-garrihy-37449759.html",
      "https://www.independent.ie/style/celebrity/celebrity-news/cheryl-dazzles-in-thigh-skimming-red-gown-during-rare-night-out-in-london-37449958.html",
      "https://www.independent.ie/style/fashion/style-talk/the-netherlands-queen-mxima-makes-the-case-for-bold-headwear-as-she-touches-down-in-london-37449963.html",
      "https://www.independent.ie/world-news/north-america/gaga-attacks-trump-gender-plan-37452418.html",
      "https://www.independent.ie/world-news/north-america/wife-of-white-nationalist-richard-spencer-accuses-him-of-physical-abuse-37452777.html",
      "https://www.independent.ie/world-news/europe/french-ban-on-islamic-veil-violates-rights-say-un-experts-37452406.html",
      "https://www.independent.ie/world-news/australasia/researcher-at-remote-russian-antarctic-station-stabs-colleague-over-tensions-in-confined-space-37452996.html",
      "https://www.independent.ie/world-news/europe/new-probe-into-sexual-abuse-by-clergy-in-us-37452409.html",
      "https://www.independent.ie/opinion/columnists/sinead-moriarty/sinead-moriarty-why-its-no-sin-to-want-a-little-notice-before-people-pop-in-37452378.html",
      "https://www.independent.ie/opinion/letters/letters-to-the-editor-eu-needs-a-trade-deal-with-britain-and-wont-be-denied-by-border-issues-37452381.html",
      "https://www.independent.ie/opinion/comment/we-are-overindulging-and-slow-to-bin-our-bad-habits-despite-all-the-warnings-37452588.html",
      "https://www.independent.ie/opinion/comment/politicians-didnt-give-a-damn-how-cuts-affected-mothers-37452392.html",
      "https://www.independent.ie/opinion/comment/vitriol-after-luas-surfing-payout-has-whiff-of-snobbery-37452384.html",
      "https://www.independent.ie/opinion/comment/brexit-isnt-the-only-challenge-facing-eu-with-poles-now-posing-new-threat-to-unity-37452404.html",
      "https://www.independent.ie/entertainment/theatre-arts/i-left-school-at-16-and-now-run-my-own-festivals-and-events-company-bram-stoker-festival-codirector-maria-schweppe-37453964.html",
      "https://www.independent.ie/entertainment/music/music-news/brian-mcfadden-was-never-going-to-be-a-part-of-tour-westlife-37452841.html",
      "https://www.independent.ie/entertainment/banter/trending/twitter-in-stitches-as-police-reveal-theyre-seeking-alleged-thief-who-looks-like-ross-geller-from-friends-37452894.html",
      "https://www.independent.ie/entertainment/theatre-arts/comedy/having-political-correctness-at-a-comedy-show-is-like-having-health-and-safety-at-a-rodeo-jimmy-carr-is-olympia-bound-37453220.html",
      "https://www.independent.ie/entertainment/television/tv-news/great-british-bake-off-has-its-three-finalists-as-tears-are-shed-over-salty-showstopper-37452872.html",
      "https://www.independent.ie/entertainment/television/tv-news/id-choose-strictly-come-dancing-over-dancing-with-the-stars-keith-duffy-37452850.html",
      "https://www.independent.ie/entertainment/television/tv-news/robbie-williams-may-finally-reunite-with-take-that-on-the-x-factor-stage-37452976.html",
      "https://www.independent.ie/entertainment/television/tv-news/everyones-freaked-by-netflixs-haunting-of-hill-house-including-crazed-cast-37453101.html",
      "https://www.independent.ie/life/travel/travel-talk/how-far-do-planes-fall-during-turbulence-and-where-in-the-world-is-it-most-common-37452778.html",
      "https://www.independent.ie/life/travel/ireland/first-look-thrillseekers-are-in-for-a-treat-at-irelands-scariest-new-tourist-attraction-37445901.html",
      "https://www.independent.ie/life/travel/travel-news/irish-distillery-and-driving-school-among-lonely-planets-top-tips-for-2019-37445442.html",
      "https://www.independent.ie/life/travel/ireland/shining-a-light-on-county-down-our-short-break-in-a-lighthouse-keepers-cottage-37439352.html",
      "https://www.independent.ie/life/travel/deals/magic-monday-fly-to-new-york-from-99-in-our-top-5-travel-deals-37444202.html",
      "https://www.independent.ie/life/travel/travel-tv/watch-walk-to-a-haunted-house-in-the-dublin-mountains-it-takes-just-1-5-hours-35857964.html",
      "https://www.independent.ie/life/food-drink/recipes/indy-power-chickpea-gnocchi-pomodoro-a-delicious-twist-on-the-classic-37429826.html",
      "https://www.independent.ie/life/health-wellbeing/healthy-eating/vegetarian-products-have-more-salt-than-seawater-37448383.html",
      "https://www.independent.ie/life/food-drink/recipes/clodagh-mckenna-creamy-haddock-chowder-inspired-by-wild-west-cork-37428734.html",
      "https://www.independent.ie/life/chard-and-ricotta-lasagne-by-william-murray-and-james-kavanagh-37404058.html",
      "https://www.independent.ie/life/food-drink/are-sweetbreads-pancreas-and-thymus-glands-making-a-comeback-uk-supermarket-releases-a-readymeal-37431340.html",
      "https://www.independent.ie/life/food-drink/i-slept-beside-the-wine-boxes-for-a-year-and-now-i-have-a-michelin-star-irish-restaurant-owner-on-what-it-takes-to-win-the-coveted-star-37425801.html",
      "https://www.independent.ie/life/gbbo-judge-prue-leith-im-78-i-can-do-what-i-like-now-37431863.html",
      "https://www.independent.ie/life/food-drink/recipes/recipes-from-iran-persian-dal-salad-and-a-beautiful-bean-dish-37429831.html",
      "https://www.independent.ie/life/motoring/car-news/report-reveals-76pc-of-used-imports-are-diesel-as-emissions-row-rages-37450370.html",
      "https://www.independent.ie/life/motoring/car-news/rsa-expert-an-indication-of-how-poor-we-are-at-signalling-what-were-going-to-do-37450372.html",
      "https://www.independent.ie/life/motoring/car-news/born-to-drive-irish-racing-driver-james-19-is-an-example-to-us-all-37450383.html",
      "https://www.independent.ie/life/motoring/car-news/new-research-prompts-question-are-safer-cars-more-dangerous-37450376.html",
      "https://www.independent.ie/life/motoring/car-news/car-cover-are-fewer-consumers-prepared-to-take-complaint-route-37450371.html",
      "https://www.independent.ie/life/motoring/car-news/motoring-inbriefs-i-saw-parents-leaving-their-young-boy-alone-in-their-car-37450374.html",
      "https://www.independent.ie/life/motoring/car-news/how-you-buy-and-maintain-your-volkswagen-is-going-to-change-fundamentally-over-the-next-few-years-37450380.html",
      "https://www.independent.ie/life/family/prince-george-5-is-taking-ballet-lessons-at-his-school-and-he-loves-it-doting-dad-william-says-37450273.html",
      "https://www.independent.ie/life/health-wellbeing/functional-medicine-is-it-the-future-of-healthcare-or-just-another-wellness-trend-37437566.html",
      "https://www.independent.ie/life/home-garden/homes/revamped-dun-laoghaire-semi-has-huge-appeal-for-young-families-37435246.html",
      "https://www.independent.ie/life/family/parenting/new-irish-mums-report-feeling-lonely-fatigued-and-anxious-new-study-37449024.html",
      "https://www.independent.ie/life/i-had-some-dark-moments-irish-mum-45-who-trained-in-her-kitchen-completes-gruelling-world-ironman-championship-37450056.html",
      "https://www.independent.ie/life/health-wellbeing/i-thought-my-tiredness-was-normal-but-it-was-a-symptom-of-a-very-rare-condition-37437567.html",
      "https://www.independent.ie/life/health-wellbeing/200-irish-people-died-last-year-leading-researcher-issues-vaccine-warning-before-winter-37449244.html",
      "https://www.independent.ie/life/home-garden/fixer-upper-home-a-threebedroom-period-terrace-in-dublin-6-for-350k-if-youre-prepared-to-put-the-work-in-37430775.html",
      "https://www.independent.ie/life/home-garden/homes/greystones-4bed-home-sold-for-505k-last-year-now-its-on-the-market-for-675k-37430729.html",
      "https://www.independent.ie/business/technology/net-alert-ireland-reports-high-rates-of-online-crime-as-half-of-users-affected-by-illegal-activity-37451365.html",
      "https://www.independent.ie/business/personal-finance/pensions/overreliance-on-generous-state-pension-set-to-come-under-serious-strain-global-index-37448340.html",
      "https://www.independent.ie/business/technology/news/netflix-set-to-issue-2bn-of-junk-bonds-to-fund-new-programmes-37446563.html",
      "https://www.independent.ie/business/technology/twitter-thought-i-got-hacked-tesla-chief-elon-musk-said-twitter-had-locked-his-account-37449096.html",
      "https://www.independent.ie/business/technology/little-and-kerr-launch-userdriven-subscription-news-app-37451366.html",
      "https://www.independent.ie/business/personal-finance/property-mortgages/time-to-reimagine-our-cities-we-need-to-build-up-not-semids-dermot-bannon-37448369.html",
      "https://www.independent.ie/irish-news/politics/women-with-children-hit-harder-than-men-by-austerity-budgets-37452394.html",
      "https://www.independent.ie/business/personal-finance/property-mortgages/threeyear-wait-for-permission-for-family-keen-to-build-new-house-37448364.html",
      "https://www.independent.ie/business/small-business/irish-fintech-company-perfectcard-confirms-its-sale-to-australias-eml-for-6m-37444230.html",
      "https://www.independent.ie/business/small-business/entreprenuer-is-toast-of-hospitality-industry-with-her-stafffinding-app-37441689.html",
      "https://www.independent.ie/business/small-business/latest-news/minister-confirms-changes-in-scheme-to-help-smes-37436257.html",
      "https://www.independent.ie/sponsored-features/taking-the-leap-37425441.html",
      "https://www.independent.ie/sponsored-features/you-could-win-1bn-in-lottery-prizes-this-week-without-leaving-ireland-37409136.html",
      "https://www.independent.ie/sponsored-features/international-dental-clinic-of-the-year-2018-winner-announced-37381333.html",
      "https://www.independent.ie/sponsored-features/helping-you-to-find-your-fit-37308831.html",
      "https://www.independent.ie/sponsored-features/live-life-and-treat-yourself-guiltfree-37304577.html",
      "https://www.independent.ie/sponsored-features/win-a-training-session-for-your-gaa-team-with-allireland-winning-cork-footballer-daniel-goulding-37157805.html",
      "https://www.independent.ie/sponsored-features/calm-after-the-wild-37101043.html",
      "https://www.independent.ie/sponsored-features/irelands-rivers-lakes-and-beaches-natural-treasures-for-us-all-to-enjoy-36756026.html",
      "https://www.independent.ie/sponsored-features/rethinking-consumption-our-choices-can-make-a-difference-36709390.html",
    ).map(Uri.unsafeFromString)

    val parsed = parse(
      new IndependentIeArticleListParser(),
      Uri.uri("http://example.com/"),
      "parsers/independent.ie/index.html"
    )

    assert(expected == parsed)
  }

}
